FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json ./

RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .

ARG ci_build=dev
ARG VITE_BLOCKS_API_URL
ARG VITE_BLOCKS_PROJECT_KEY
ARG VITE_BLOCKS_X_BLOCKS_KEY
ARG VITE_BLOCKS_APP_DOMAIN
ARG VITE_BLOCKS_OIDC_URL=https://iam.seliseblocks.com
ARG VITE_BLOCKS_OIDC_CLIENT_ID
ARG VITE_BLOCKS_OIDC_SCOPE="openid profile"
ARG VITE_BLOCKS_REDIRECT_URI
ARG VITE_BLOCKS_HOSTED_LOGIN=true
ARG NEXT_PUBLIC_BLOCKS_API_URL
ARG NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY
ARG NEXT_PUBLIC_BLOCKS_APP_DOMAIN
ARG NEXT_PUBLIC_BLOCKS_OIDC_URL
ARG NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID
ARG NEXT_PUBLIC_BLOCKS_DEV_HOST

ENV VITE_BLOCKS_API_URL=${VITE_BLOCKS_API_URL}
ENV VITE_BLOCKS_PROJECT_KEY=${VITE_BLOCKS_PROJECT_KEY}
ENV VITE_BLOCKS_X_BLOCKS_KEY=${VITE_BLOCKS_X_BLOCKS_KEY}
ENV VITE_BLOCKS_APP_DOMAIN=${VITE_BLOCKS_APP_DOMAIN}
ENV VITE_BLOCKS_OIDC_URL=${VITE_BLOCKS_OIDC_URL}
ENV VITE_BLOCKS_OIDC_CLIENT_ID=${VITE_BLOCKS_OIDC_CLIENT_ID}
ENV VITE_BLOCKS_OIDC_SCOPE=${VITE_BLOCKS_OIDC_SCOPE}
ENV VITE_BLOCKS_REDIRECT_URI=${VITE_BLOCKS_REDIRECT_URI}
ENV VITE_BLOCKS_HOSTED_LOGIN=${VITE_BLOCKS_HOSTED_LOGIN}
ENV NEXT_PUBLIC_BLOCKS_API_URL=${NEXT_PUBLIC_BLOCKS_API_URL}
ENV NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY=${NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY}
ENV NEXT_PUBLIC_BLOCKS_APP_DOMAIN=${NEXT_PUBLIC_BLOCKS_APP_DOMAIN}
ENV NEXT_PUBLIC_BLOCKS_OIDC_URL=${NEXT_PUBLIC_BLOCKS_OIDC_URL}
ENV NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID=${NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID}
ENV NEXT_PUBLIC_BLOCKS_DEV_HOST=${NEXT_PUBLIC_BLOCKS_DEV_HOST}

RUN NEXT_PUBLIC_BLOCKS_API_URL="${NEXT_PUBLIC_BLOCKS_API_URL:-$VITE_BLOCKS_API_URL}" \
    NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY="${NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY:-${VITE_BLOCKS_X_BLOCKS_KEY:-$VITE_BLOCKS_PROJECT_KEY}}" \
    NEXT_PUBLIC_BLOCKS_APP_DOMAIN="${NEXT_PUBLIC_BLOCKS_APP_DOMAIN:-$VITE_BLOCKS_APP_DOMAIN}" \
    NEXT_PUBLIC_BLOCKS_OIDC_URL="${NEXT_PUBLIC_BLOCKS_OIDC_URL:-$VITE_BLOCKS_OIDC_URL}" \
    NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID="${NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID:-$VITE_BLOCKS_OIDC_CLIENT_ID}" \
    NODE_OPTIONS="--max-old-space-size=4096" \
    npm run build

FROM node:22-alpine AS runner

RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 8080

CMD ["node", "server.js"]
